[package]
name = "rocket-multipart-form-data"
version = "0.4.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-multipart-form-data"
homepage = "https://magiclen.org/rocket-multipart-form-data"
keywords = ["rocket", "server", "web", "multipart", "form-data"]
categories = ["parsing"]
description= "This crate provides a multipart parser for the Rocket framework."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/rocket-multipart-form-data", branch = "master" }

[dependencies]
rocket = "0.4"
mime = "0.3.12"
multipart = "0.15.3"
chrono = "0.4.6"

rocket-include-static-resources = "0.7"
rocket-raw-response = "0.3"

lazy_static = "1.2.0"
lazy-static-include = "1.2.1"
