[package]
name = "rocket-multipart-form-data"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-multipart-form-data"
homepage = "https://magiclen.org/rocket-multipart-form-data"
keywords = ["rocket", "server", "web", "multipart"]
categories = ["parsing"]
description= "This crate provides a multipart parser."
readme = "README.md"
license = "MIT"

[dependencies]
rocket = "0.3.16"
multipart = "0.15.3"
tempdir = "0.3.7"

[dev-dependencies]
rocket_codegen = "0.3.16"