[package]
name = "rocket-multipart-form-data"
version = "0.10.0"
edition = "2018"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-multipart-form-data"
homepage = "https://magiclen.org/rocket-multipart-form-data"
keywords = ["rocket", "server", "web", "multipart", "form-data"]
categories = ["parser-implementations"]
description = "This crate provides a multipart parser for the Rocket framework."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev" }
mime = "0.3.12"
multer = { git = "https://github.com/rousan/multer-rs" }
tokio-util = "0.6.6"

[dev-dependencies]
rocket-include-static-resources = { git = "https://github.com/magiclen/rocket-include-static-resources", version = "0.10" }
rocket-raw-response = { git = "https://github.com/magiclen/rocket-raw-response", version = "0.5" }