[package]
name = "rocket-multipart-form-data"
version = "0.9.2"
edition = "2018"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-multipart-form-data"
homepage = "https://magiclen.org/rocket-multipart-form-data"
keywords = ["rocket", "server", "web", "multipart", "form-data"]
categories = ["parser-implementations"]
description= "This crate provides a multipart parser for the Rocket framework."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/rocket-multipart-form-data"
branch = "master"

[dependencies]
rocket = "0.4.2"
mime = "0.3.12"
multipart = {version = "0.16.1", default-features = false, features = ["server"]}

[dependencies.educe]
version = ">=0.4.2"
features = ["PartialEq", "Eq", "PartialOrd", "Ord"]
default-features = false

[dev-dependencies]
rocket-include-static-resources = "0.8"
rocket-raw-response = "0.4"